### ISSUE TITLE
Merge back

### ISSUE THREAD

**Issue by enter-dragon** [eupnea-linux-backup/depthcharge-guide#1]
Merge PR https://github.com/enter-dragon/depthcharge-guide/commit/1cd81e714f780d3be9b04b76334f6e4b5f65f5fe
or individual commit: https://github.com/enter-dragon/depthcharge-guide/commit/1992c9cbf724abb6158ff0d95f772d597a0b48d2

**Comment by Apacelus** [comment]
Thank you for your work. You have been added to the contributors list and I just merged most of your changes.
